name: svf-teaching

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      XCODE_VERSION: '15.3.0'
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      # checkout the repo
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          
      # setup the environment 
      - name: mac-setup
        if: runner.os == 'macOS'
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}
      - name: mac-setup-workaround
        if: runner.os == 'macOS'
        run: ln -sfn /Applications/Xcode_${{ env.XCODE_VERSION }}.app /Applications/Xcode.app
      - name: ubuntu-setup
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install cmake gcc g++ nodejs doxygen graphviz
          
      # install llvm and svf
      - name: env-setup
        run: |
          npm install svf-lib
          git clone https://github.com/Johanmyst/SVF.git -b build-fixes
          cd SVF
          source build.sh
          # export SVF_DIR, LLVM_DIR, Z3_DIR for later use 
          export SVF_DIR=$GITHUB_WORKSPACE/SVF >> $GITHUB_ENV
          export LLVM_DIR=$GITHUB_WORKSPACE/SVF/llvm-16.0.0.obj >> $GITHUB_ENV
          export Z3_DIR=$GITHUB_WORKSPACE/SVF/z3.obj >> $GITHUB_ENV
          
      # build current repo
      - name: build-svf
        run: |
         cmake . -DSVF_DIR=$GITHUB_WORKSPACE/SVF -DLLVM_DIR=$GITHUB_WORKSPACE/SVF/llvm-16.0.0.obj -DZ3_DIR=$GITHUB_WORKSPACE/SVF/z3.obj
         make 
